
baseURL = "https://pmikus.github.io/"
googleanalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "section"]

[module]
[[module.imports]]
path = "github.com/kaiiiz/hugo-theme-monochrome"

[params]
  # set to change date format
  dateFormat = "2.1.2006"
  # backgroundPath = "images/bg.jpg"

[languages]
[languages.sk]
  languageName = "Slovak"
  languageCode = "sk-sk"
  title = "pmks"
[languages.en]
  languageName = "English"
  languageCode = "en-us"
  title = "pmks"