
baseURL = "https://pmikus.github.io/pmikus/"
googleanalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "section"]

[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 100
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true

[module]
  [module.hugoVersion]
    min = "0.121.2"
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[menu]
  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/pmikus/"
    weight = 3

[params]
  defaultTheme = "light"
  description = "pmks gallery"
  title = "pmks gallery"
  [params.author]
    email = "peter.mikus"
    name = "Peter Mikus"
  [params.socialIcons]
    500px = "https://www.instagram.com/"
    github = "https://github.com/pmikus/"
    email = "mailto:peter.mikus"
  [params.gallery]
    boxSpacing = 10
    targetRowHeight = 288
    targetRowHeightTolerance = 0.25

[languages]
[languages.sk]
  languageName = "Slovak"
  languageCode = "sk-sk"
  title = "pmks"
[languages.en]
  languageName = "English"
  languageCode = "en-us"
  title = "pmks"