
baseURL = "https://pmikus.github.io/pmikus/"
googleanalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "section"]

[outputs]
  home = ["HTML"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 100
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true

[module]
  [module.hugoVersion]
    min = "0.121.2"
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[menu]
  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/nicokaiser/hugo-theme-gallery/"
    weight = 3

[params]
  defaultTheme = "dark"
  description = "Example site for hugo-theme-gallery"
  title = "My Gallery"
  [params.author]
    email = "user@example.com"
    name = "Your Name"
  [params.socialIcons]
    facebook = "https://www.facebook.com/"
    instagram = "https://www.instagram.com/"
    github = "https://github.com/pmikus/"
    youtube = "https://www.youtube.com/"
    email = "mailto:user@example.com"
  [params.gallery]
    #boxSpacing = 10
    #targetRowHeight = 288
    #targetRowHeightTolerance = 0.25

[languages]
[languages.sk]
  languageName = "Slovak"
  languageCode = "sk-sk"
  title = "pmks"
[languages.en]
  languageName = "English"
  languageCode = "en-us"
  title = "pmks"