
baseURL = "https://pmikus.github.io/pmikus/"
googleanalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "section"]

[module]
[[module.imports]]
path = "github.com/kaiiiz/hugo-theme-monochrome"

[params]
  # set to change date format
  dateFormat = "2.1.2006"
  # backgroundPath = "images/bg.jpg"
  footer = "Copyright © 2025 by pmikus" # default: None

[languages]
[languages.sk]
  languageName = "Slovak"
  languageCode = "sk-sk"
  title = "pmks"
[languages.en]
  languageName = "English"
  languageCode = "en-us"
  title = "pmks"